# Configuration file of HP OM REST API Extension
userName: "AppDynamics"
password: "crimson"

# Location of opcmsg executable, e.g. "C:\\HP\\bin\\opcmsg"
pathToExecutable: "/Downloads/license.lic"


# Message group for HP OpenView opcmsg
msgGroup: "AppDynamics"

# Default server values
server:
    applicationConnectors:
        - type: http
          port: 8085
        - type: https
          port: 8443  
          keyStorePath: //Library//Java//JavaVirtualMachines//jdk1.7.0_55.jdk//Contents//Home//jre//lib//security//cacerts
          keyStorePassword: changeit
          validateCerts: false
    
# Logging settings
logging:
  # The default level of all loggers. Can be OFF, ERROR, WARM, INFO, DEBUG, TRACE, or ALL
  level: INFO
  
  # Logger-specific levels.
  loggers:
  
    # Sets the level for 'com.example.app' to DEBUG
    com.appdynamics.extension: DEBUG
  
  appenders:
    - type: console
    - type: syslog
      threshold: INFO
      host: localhost
      port: 514
      facility: local0
    - type: file
      currentLogFilename:  ./logs/hpOM.log
      archivedLogFilenamePattern: ./logs/hpOM-%d.log.gz
      archivedFileCount: 7

